name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: openrndr/setup-opengl@v1
    - run: xvfb-run glxinfo
    - name: cmake
      run: cmake . -DCARDBOARD_GRAPHICS_TARGET:STRING=opengl
    - name: make
      run: make
