name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: openrndr/setup-opengl@v1
    - run: |
        sudo apt-get install libgl1-mesa-dev libglm-dev libglfw3-dev libxinerama
        xvfb-run glxinfo
    - name: cmake
      run: cmake . -DCARDBOARD_GRAPHICS_TARGET=opengl -DCARDBOARD_RESOURCES_WINDOWS_TARGET=glfw
    - name: make
      run: make
